# Generated by Django 5.1.7 on 2025-05-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customeraddress_options_remove_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.IntegerField(default=0),
        ),
    ]
