# Generated by Django 5.1.7 on 2025-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='to_cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
