# Generated by Django 5.1.7 on 2025-06-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_to_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document',
        ),
    ]
