# Generated by Django 5.1.7 on 2025-05-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cart_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='disabled_at',
        ),
    ]
