# Generated by Django 5.1.7 on 2025-03-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_customerandress_customeradress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAdress',
            new_name='CustomerAddress',
        ),
    ]
