# Generated by Django 5.1.7 on 2025-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_customeradress_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
