# Generated by Django 5.1.7 on 2025-04-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customer_number_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
