# Generated by Django 5.1.7 on 2025-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=dict),
        ),
    ]
