# Generated by Django 5.1.7 on 2025-05-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_main',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
