# Generated by Django 5.1.7 on 2025-05-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customeraddress_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
