# Generated by Django 5.1.7 on 2025-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cartitem_options_user_document_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10),
        ),
    ]
