# Generated by Django 5.1.7 on 2025-07-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
